name: auto_form_plus
description: AutoForm build simple forms.

repository: "https://www.github.com/kld/auto_form"

version: 0.3.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^10.3.2
  image_picker: ^1.0.8
  syncfusion_flutter_pdfviewer: ^30.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
